content/urls.py
from django.urls import path
from .views import add_author, add_quote, user_quotes_list, author_details_user

app_name = 'content'

urlpatterns = [
    path('add-author/', add_author, name='add_author'),
    path('add-quote/', add_quote, name='add_quote'),
    path('user-quotes/', user_quotes_list, name='user_quotes_list'),
    path('user-author/<str:id_>/', author_details_user, name='author_details_user'),
]

hw_dj_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('content/', include('content.urls', namespace='content')),
]

quotes/urls.py
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='root'),
    path('<int:page>', views.main, name='root_paginate'),
    path('author/<str:id_>/', views.author_details, name='author_details'),
]

users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', 
        PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), 
        name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
        success_url='/users/reset-password/complete/'),
        name='password_reset_confirm'),
    path('reset-password/complete/',
        PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete')
]

content/models.py
from django.db import models
from django.conf import settings

class Author(models.Model):
    name = models.CharField(max_length=100)
    born_date = models.DateField(null=True, blank=True) 
    born_location = models.CharField(max_length=100, blank=True) 
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

class Quote(models.Model):
    text = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.text




users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    first_name = None
    last_name = None
    email = models.EmailField(unique=True, null=True, blank=True)

content/forms.py
from django import forms
from .models import Author, Quote

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name', 'born_date', 'born_location', 'description']

class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['text', 'author']




users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser

class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    email = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2']

class UserLoginForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password']

content/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import AuthorForm, QuoteForm
from .models import Quote
from django.http import HttpResponseNotFound
from .models import Author

@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('content:add_quote')
    else:
        form = AuthorForm()
    return render(request, 'content/add_author.html', {'form': form})

@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            quote = form.save(commit=False)
            quote.user = request.user 
            quote.save()
            return redirect('content:user_quotes_list') 
    else:
        form = QuoteForm()
    return render(request, 'content/add_quote.html', {'form': form})

def user_quotes_list(request):
    user_quotes = Quote.objects.filter(user__isnull=False)
    return render(request, 'content/user_quotes_list.html', {'user_quotes': user_quotes})

def author_details_user(request, id_):
    try:
        author = Author.objects.get(pk=id_) 
        return render(request, 'content/author_details_user.html', {'author': author})
    except Author.DoesNotExist:
        return HttpResponseNotFound("Author not found")
    except ValueError:
        return HttpResponseNotFound("Invalid ID format")




quotes/views.py
from bson.objectid import ObjectId
from django.contrib.auth.models import User
from django.shortcuts import render
from .utils import get_mongodb
from django.core.paginator import Paginator

def main(request, page=1):
    db = get_mongodb()
    quotes_cursor = db['quote'].find()  
    quotes = list(quotes_cursor) 
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    #print(quotes)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})

def author_details(request, id_):
    db = get_mongodb()
    author = db['author'].find_one({'_id': ObjectId(id_)})
    if not author:
        return render(request, '404.html', status=404)
    return render(request, 'quotes/author_details.html', {'author': author})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from .forms import UserRegistrationForm, UserLoginForm
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

def register_view(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('quotes:root')
    else:
        form = UserRegistrationForm()
    return render(request, 'users/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = UserLoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('quotes:root')
    else:
        form = UserLoginForm()
    return render(request, 'users/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('quotes:root')



class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

content/templates/content/add_author.html
{% extends "quotes/base.html" %}

{% block content %}

  <h2>Add Author</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add</button>
  </form>
  
{% endblock %}

content/templates/content/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}

  <h2>Add quote</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add</button>
  </form>

{% endblock %}

content/templates/content/author_details_user.html
{% extends 'quotes/base.html' %}

{% block content %} 

<div class="author-details">
    <h3 class="author-title">{{ author.author }}</h3>
    <p><strong>Born:</strong> 
        <span class="author-born-date">{{ author.born_date }}</span> 
        <span class="author-born-location">{{ author.born_location }}</span>
    </p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{ author.description }}
    </div>
</div>

{% endblock %}

content/templates/content/user_quotes_list.html
{% extends "quotes/base.html" %}

{% block content %}

<h1>Цитати користувачів</h1>

{% for quote in user_quotes %}
<div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
    <span class="text" itemprop="text">“{{ quote.text }}”</span>
    <span>by <small class="author" itemprop="author">{{ quote.author.name }}</small>
    <a href="{% url 'content:author_details_user' quote.author.id %}" previewlistener="true">(about)</a>
    </span>
    <div class="tags">
        Tags:
        <meta class="keywords" itemprop="keywords" content="{{ quote.keywords|join:',' }}"> 

        {% for keyword in quote.keywords %}
            <a class="tag" href="{% url 'keyword_detail' keyword %}" previewlistener="true">{{ keyword }}</a>
        {% endfor %}
    </div>
</div>
{% empty %}
    <p>Цитати відсутні.</p>
{% endfor %}

{% endblock %}

quotes/templates/quotes/author_details.html
{% extends 'quotes/base.html' %}

{% block content %} 

<div class="author-details">
    <h3 class="author-title">{{ author.author }}</h3>
    <p><strong>Born:</strong> 
        <span class="author-born-date">{{ author.born_date }}</span> 
        <span class="author-born-location">{{ author.born_location }}</span>
    </p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{ author.description }}
    </div>
</div>

{% endblock %}

quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Homework</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none" previewlistener="true">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    {% if user.is_authenticated %}
                        <a href="{% url 'users:logout' %}">Logout</a>
                        <a href="{% url 'content:add_author' %}" class="btn btn-secondary ms-2">Add Author</a>
                    {% else %}
                        <a href="{% url 'users:login' %}">Login</a>
                        <a href="{% url 'users:register' %}">Register</a>
                    {% endif %}

                    <a href="{% url 'content:user_quotes_list' %}" class="btn btn-primary ms-2">QUOTES FROM USERS</a>
                </p>
            </div>
        </div>
    

        {% block content %} {% endblock %}

    </div>
</body>
</html>

quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">
            {{quote.quote}}
        </span>
        <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
        <a href="/author/{{quote.author}}" previewlistener="true">(about)</a>
        </span>
        <div class="keywords">
            Keywords:
            {% for keyword in quote.keywords %}
            <a class="keyword" href="/keyword/{{keyword}}" previewlistener="true">{{keyword}}</a>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
    <nav>
        <ul class="pager">
            
            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                   href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}" previewlistener="true">
                    <span aria-hidden="true">←</span> Previous
                </a>
            </li>
            
            
            <li class="next">
                <a class="{% if not quotes.has_next %} disabled {% endif %}"
                   href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}" previewlistener="true">
                    Next <span aria-hidden="true">→</span></a>
            </li>
            
        </ul>
    </nav>
    </div>
    <div class="col-md-4 tags-box">
        
            <h2>Top Ten keywords</h2>
            
            <span class="keyword-item">
            <a class="keyword" style="font-size: 28px" href="/keyword/love/" previewlistener="true">love</a>
            </span>
            
            <span class="keyword-item">
            <a class="keyword" style="font-size: 26px" href="/keyword/inspirational/" previewlistener="true">inspirational</a>
            </span>
            
            <span class="keyword-item">
            <a class="keyword" style="font-size: 26px" href="/keyword/life/" previewlistener="true">life</a>
            </span>
            
            <span class="keyword-item">
            <a class="keyword" style="font-size: 24px" href="/keyword/humor/" previewlistener="true">humor</a>
            </span>
            
            <span class="keyword-item">
            <a class="keyword" style="font-size: 22px" href="/keyword/books/" previewlistener="true">books</a>
            </span>
            
            <span class="keyword-item">
            <a class="keyword" style="font-size: 14px" href="/keyword/reading/" previewlistener="true">reading</a>
            </span>
            
            <span class="keyword-item">
            <a class="keyword" style="font-size: 10px" href="/keyword/friendship/" previewlistener="true">friendship</a>
            </span>
            
            <span class="keyword-item">
            <a class="keyword" style="font-size: 8px" href="/keyword/friends/" previewlistener="true">friends</a>
            </span>
            
            <span class="keyword-item">
            <a class="keyword" style="font-size: 8px" href="/keyword/truth/" previewlistener="true">truth</a>
            </span>
            
            <span class="keyword-item">
            <a class="keyword" style="font-size: 6px" href="/keyword/simile/" previewlistener="true">simile</a>
            </span>
            
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/login.html
{% extends 'quotes/base.html' %}
{% block content %}

<h2>Login</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Log In</button>
    <div class="small text-center">
        <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
</form>

{% endblock %}

users/templates/users/password_reset.html
{% extends 'quotes/base.html' %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'quotes/base.html' %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'quotes/base.html' %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'quotes/base.html' %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

users/templates/users/register.html
{% extends 'quotes/base.html' %}
{% block content %}

<div>
    <h2>Register</h2>
</div>

<form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <div>
        <label> Email:
            {{ form.email }}
        </label>
        <span>{{ form.errors.email }}</span>
    </div>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}